"""The Vizcaya Bridge's drawing for the integration hero, from FLUX's elevation to the two WebPs.

Input: the architect's elevation FLUX.2 [dev] drew from the photograph's bridge cut-out (seed 21,
2016 x 1344, the photograph's own frame; not committed, it is regenerated by the prompt in the
issue). Steps:

1. ink to alpha: dark ink on white paper, a = clip((0.88 - grey) / 0.55, 0, 1);
2. the Las Arenas tower is moved onto the photograph's: FLUX drew it about 10 px left at the top
   and 45 px narrower at the base than the tower it replaces (landmarks in bridge.py), so each row
   of it is stretched between the photograph's legs, fading back to the drawing 80 px either side;
3. tinted a step under the section's red (#D8432F against #EA4335): the bridge and its connectors
   read as one thing, and the drawing stands out on the band like the lighthouse (founder,
   2026-10-02: "tiene que destacar… ambos colores bastante similares"; the deep #A8352B before it
   barely showed through the veil). The stroke is the drawing's own, fine like the lighthouse's:
   thickened, it read as a smudge;
4. cut to the band the ink occupies (rows 378-998), so the drawing never outsizes the banks and
   never becomes the page's largest paint.

    python3 docs/design/hero-rotativo/bridge_plan.py <flux-elevation.jpg>
"""
import os, sys
import numpy as np
from PIL import Image

RED = (0xD8, 0x43, 0x2F)
TOP, BOTTOM = 378, 998
# the Las Arenas tower's outer legs: the drawing's, measured on its alpha, and the photograph's (bridge.py)
DRAWN = ((405, 1685, 1725), (870, 1670, 1753))
PHOTO = ((405, 1692, 1736), (905, 1645, 1780))
FADE = 80


def legs(pair, y):
    (y0, l0, r0), (y1, l1, r1) = pair
    t = min(max((y - y0) / (y1 - y0), 0.0), 1.0)
    return l0 + (l1 - l0) * t, r0 + (r1 - r0) * t


def move_tower(a):
    h, w = a.shape
    out = a.copy()
    xs = np.arange(w, dtype=np.float64)
    for y in range(360, 1000):
        ld, rd = legs(DRAWN, y)
        lp, rp = legs(PHOTO, y)
        src = ld + (xs - lp) * (rd - ld) / (rp - lp)
        shift = src - xs
        # full correction between the photograph's legs, fading to none FADE px outside them
        k = np.clip(1 - np.maximum(lp - xs, xs - rp) / FADE, 0, 1)
        k[(xs >= lp) & (xs <= rp)] = 1
        out[y] = np.interp(xs + shift * k, xs, a[y])
    return out


def main(src):
    grey = np.asarray(Image.open(src).convert("L"), dtype=np.float64) / 255
    a = np.clip((0.88 - grey) / 0.55, 0, 1)
    a = move_tower(a)
    a = (a * 255).astype(np.uint8)
    rgba = np.dstack([np.full(a.shape + (3,), RED, np.uint8), a])
    band = Image.fromarray(rgba).crop((0, TOP, a.shape[1], BOTTOM))
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, "..", "..", "..", "public", "assets", "hero"))
    for width, name in ((1320, "int-puente-plan.webp"), (960, "int-puente-plan-960.webp")):
        img = band.resize((width, round(width * (BOTTOM - TOP) / a.shape[1])), Image.LANCZOS)
        img.save(os.path.join(out, name), "WEBP", quality=70, alpha_quality=70, method=6)
        print(name, img.size, os.path.getsize(os.path.join(out, name)), "bytes")


if __name__ == "__main__":
    main(sys.argv[1])
